[package]
name = "read_elf"
version = "0.1.0"
authors = ["chris huang <youth7@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# [[bin]]
# name = "read_elf"
# path = "read_elf.rs"
